# Query to find all people with labels, descriptions, and counts

PREFIX ecrm: <http://erlangen-crm.org/current/> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX slb: <http://sloanelab.org/>

SELECT ?person ?label ?desc (COUNT(?item) AS ?count)

WHERE {
	
	# get all people
	?person a ecrm:E21_Person .

	# get catalogue items referring to people
	?item slb:SL10_specifically_refers_to ?person .

	# get people labels
	?person rdfs:label ?label .

	# get people descriptions
	?person rdfs:comment ?desc .
}

GROUP BY ?person ?label ?desc

ORDER BY ?label
